name: Bump version

on:
  pull_request:
    branches:
      - main

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0


      - name: Set up Python
        uses: actions/setup-python@v2  # Use setup-python action
        with:
          python-version: '3.x'       # Specify your Python version

      - name: Install dependencies
        run: pip install toml

      - name: Install yq
        run: pip install yq

      - name: Add the pyproject file to track
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          chmod -R u+rwX pyproject.toml
          git add pyproject.toml

      - name: Verify pyproject.toml before update
        run: cat pyproject.toml

      - name: Update pyproject.toml with new version
        run: |
              version=${{ steps.cz.outputs.version }}
              sed -i "s/^version = \".*\"/version = \"$version\"/" pyproject.toml

      - name: Verify pyproject.toml version update
        run: cat pyproject.toml

      - name: Check file permissions and ownership
        run: |
          echo "Current user: $(whoami)"
          ls -la
          ls -la .git/
          ls -la .git/objects/


      - name: List modified files
        run: git status

      - name: Push changes
        run: |
          git commit -m "bump: update version to v${{ steps.cz.outputs.version }}"
          git push 
